# Generated by Django 5.0.9 on 2025-08-17 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='組織名')),
                ('phone_number', models.CharField(max_length=15, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('exist', models.BooleanField(default=True, verbose_name='存在')),
            ],
            options={
                'verbose_name': '組織',
                'verbose_name_plural': '組織',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='プラン名')),
                ('description', models.TextField(verbose_name='説明')),
                ('price', models.IntegerField(verbose_name='価格（月額円）')),
                ('max_duration', models.IntegerField(default=100, verbose_name='最大時間（分）')),
                ('stripe_price_id', models.CharField(max_length=100, verbose_name='Stripe料金ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サブスクリプションプラン',
                'verbose_name_plural': 'サブスクリプションプラン',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='メールアドレス確認日時')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='電話番号')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理者')),
                ('is_active', models.BooleanField(default=False, verbose_name='アクティブ')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='スーパーユーザー')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='トークン')),
                ('two_factor_enabled', models.BooleanField(default=True, verbose_name='2要素認証有効')),
                ('two_factor_method', models.CharField(choices=[('email', 'メール'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='2要素認証方法')),
                ('login_attempts', models.IntegerField(default=0, verbose_name='ログイン試行回数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='ロック解除時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('exist', models.BooleanField(default=True, verbose_name='存在')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='member_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, '未契約'), (1, '有効'), (2, '支払い遅延'), (3, 'キャンセル'), (4, 'トライアル')], default=0, verbose_name='ステータス')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe顧客ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripeサブスクリプション ID')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='現在の期間開始日')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='現在の期間終了日')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='期間終了時に解約')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='member_management.organization', verbose_name='組織')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='member_management.subscriptionplan', verbose_name='プラン')),
            ],
            options={
                'verbose_name': 'サブスクリプション',
                'verbose_name_plural': 'サブスクリプション',
            },
        ),
    ]
