# Generated by Django 5.0.9 on 2025-08-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_used_trial',
            field=models.BooleanField(default=False, verbose_name='トライアル使用済み'),
        ),
    ]
