# Generated by Django 5.0.9 on 2025-08-18 12:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0002_subscription_has_used_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('flyer', 'チラシ'), ('web', 'Webサイト'), ('social', 'SNS'), ('other', 'その他')], max_length=50, verbose_name='流入元')),
                ('session_id', models.CharField(help_text='Cookieなどで管理するセッションID', max_length=255, verbose_name='セッションID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='ユーザーエージェント')),
                ('referer', models.URLField(blank=True, max_length=500, null=True, verbose_name='リファラー')),
                ('accessed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='アクセス日時')),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name='登録日時')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_tracking', to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー')),
            ],
            options={
                'verbose_name': 'キャンペーントラッキング',
                'verbose_name_plural': 'キャンペーントラッキング',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['source', 'accessed_at'], name='member_mana_source_989e69_idx'), models.Index(fields=['session_id'], name='member_mana_session_80452e_idx'), models.Index(fields=['registered_user'], name='member_mana_registe_25f044_idx')],
            },
        ),
    ]
