# Generated by Django 5.0.9 on 2025-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0003_campaigntracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntracking',
            name='is_manual_referral',
            field=models.BooleanField(default=False, help_text='ユーザーが手動で流入元を選択した場合はTrue', verbose_name='手動設定'),
        ),
        migrations.AlterField(
            model_name='campaigntracking',
            name='source',
            field=models.CharField(choices=[('flyer', 'チラシ'), ('web', 'Webサイト'), ('social', 'SNS'), ('friend', '友人・知人の紹介'), ('news', 'ニュース・記事'), ('other', 'その他')], max_length=50, verbose_name='流入元'),
        ),
    ]
