# Generated by Django 5.0.9 on 2025-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0004_campaigntracking_is_manual_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntracking',
            name='campaign_code',
            field=models.CharField(blank=True, help_text='特定のキャンペーンやプロモーションの識別子', max_length=100, null=True, verbose_name='キャンペーンコード'),
        ),
        migrations.AddField(
            model_name='campaigntracking',
            name='sns_platform',
            field=models.CharField(blank=True, help_text='x, instagram, facebook, tiktok, youtube, line等', max_length=50, null=True, verbose_name='SNSプラットフォーム'),
        ),
    ]
