services:
  django:
    build: .
    image: config
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    # platform: linux/amd64
    # command: sh -c "cron -f & python manage.py runserver 0.0.0.0:${APP_PORT} --noreload" # デバッグ無
    # command: sh -c "cron -f & python manage.py runserver 0.0.0.0:${APP_PORT} --noreload" # デバッグ無
    # command: sh -c "cron -f & echo 'デバッグ待機中です...' && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} --wait-for-client -m manage runserver 0.0.0.0:${APP_PORT} --noreload --nothreading" # デバッグ有
    # command: sh -c "cron -f & python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} --wait-for-client -m manage runserver 0.0.0.0:${APP_PORT} --nothreading"
    command: sh -c "cron -f & python manage.py runserver 0.0.0.0:${APP_PORT} --nothreading"
    volumes:
      - .:/code
    networks:
      - webdev
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    depends_on:
      - redis
    mem_limit: 1.5g
    memswap_limit: 1.5g

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 512m --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - webdev
    ports:
      - "6380:6379"
    mem_limit: 1g
    memswap_limit: 1g

  celery:
    build: .
    image: config
    env_file:
      - .env
    command: celery -A config worker --loglevel=info --concurrency=1 --max-memory-per-child=2000000
    volumes:
      - .:/code
    networks:
      - webdev
    depends_on:
      - redis
      - django
    mem_limit: 4g
    memswap_limit: 4g

  zoom_bot_server:
    build: ./zoom_bot_server
    platform: linux/amd64
    env_file:
      - ./zoom_bot_server/.env
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    ports:
      - "4000:4000"
    volumes:
      - ./zoom_bot_server:/app
      - ./media/zoom_recordings:/app/media/zoom_recordings
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
    devices:
      - /dev/snd
    privileged: true
    networks:
      - webdev
    working_dir: /app
    mem_limit: 1g
    memswap_limit: 1g

volumes:
  redis_data:
  

networks:
  webdev:
    external: true
    driver: bridge
