version: '3.8'

services:
  django:
    build: .
    image: config
    extra_hosts:
      - host.docker.internal:host-gateway
    platform: linux/amd64
    command: sh -c "python manage.py runserver 0.0.0.0:8000 --noreload" # デバッグ無
    # command: sh -c "echo 'デバッグ待機中です...' && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} --wait-for-client -m manage runserver 0.0.0.0:8000" # デバッグ有
    volumes:
      - .:/code
    networks:
      - webdev
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"

networks:
  webdev:
    external: true
    driver: bridge