# Generated by Django 5.0.9 on 2025-09-02 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_management', '0005_campaigntracking_campaign_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('tracking_id', models.CharField(max_length=50, unique=True, verbose_name='トラッキングID')),
                ('domain', models.URLField(verbose_name='対象ドメイン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_projects', to='member_management.organization', verbose_name='組織')),
            ],
            options={
                'verbose_name': 'トラッキングプロジェクト',
                'verbose_name_plural': 'トラッキングプロジェクト',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, verbose_name='セッションID')),
                ('page_url', models.URLField(verbose_name='ページURL')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='ページタイトル')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='参照元URL')),
                ('user_agent', models.TextField(verbose_name='ユーザーエージェント')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IPアドレス')),
                ('screen_width', models.IntegerField(blank=True, null=True, verbose_name='画面幅')),
                ('screen_height', models.IntegerField(blank=True, null=True, verbose_name='画面高')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.trackingproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'ページビュー',
                'verbose_name_plural': 'ページビュー',
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField(verbose_name='ページURL')),
                ('x_coordinate', models.IntegerField(verbose_name='X座標')),
                ('y_coordinate', models.IntegerField(verbose_name='Y座標')),
                ('click_count', models.IntegerField(default=0, verbose_name='クリック数')),
                ('hover_count', models.IntegerField(default=0, verbose_name='ホバー数')),
                ('date', models.DateField(verbose_name='集計日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_data', to='analytics.trackingproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'ヒートマップデータ',
                'verbose_name_plural': 'ヒートマップデータ',
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('click', 'クリック'), ('scroll', 'スクロール'), ('mousemove', 'マウス移動'), ('mouseenter', 'マウス進入'), ('mouseleave', 'マウス離脱'), ('resize', 'ウィンドウサイズ変更'), ('focus', 'フォーカス'), ('blur', 'フォーカス離脱')], max_length=20, verbose_name='イベントタイプ')),
                ('x_coordinate', models.IntegerField(blank=True, null=True, verbose_name='X座標')),
                ('y_coordinate', models.IntegerField(blank=True, null=True, verbose_name='Y座標')),
                ('scroll_percentage', models.FloatField(blank=True, null=True, verbose_name='スクロール率(%)')),
                ('element_selector', models.TextField(blank=True, null=True, verbose_name='要素セレクタ')),
                ('element_text', models.TextField(blank=True, null=True, verbose_name='要素テキスト')),
                ('viewport_width', models.IntegerField(blank=True, null=True, verbose_name='ビューポート幅')),
                ('viewport_height', models.IntegerField(blank=True, null=True, verbose_name='ビューポート高')),
                ('timestamp', models.DateTimeField(verbose_name='イベント発生時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('page_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='analytics.pageview', verbose_name='ページビュー')),
            ],
            options={
                'verbose_name': 'ユーザーインタラクション',
                'verbose_name_plural': 'ユーザーインタラクション',
            },
        ),
        migrations.CreateModel(
            name='ScrollDepth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField(verbose_name='ページURL')),
                ('depth_percentage', models.IntegerField(verbose_name='スクロール深度(%)')),
                ('user_count', models.IntegerField(default=0, verbose_name='ユーザー数')),
                ('date', models.DateField(verbose_name='集計日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scroll_depths', to='analytics.trackingproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'スクロール深度',
                'verbose_name_plural': 'スクロール深度',
                'indexes': [models.Index(fields=['project', 'page_url', 'date'], name='analytics_s_project_a54381_idx')],
                'unique_together': {('project', 'page_url', 'depth_percentage', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['project', 'created_at'], name='analytics_p_project_45e9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_id'], name='analytics_p_session_a580f2_idx'),
        ),
        migrations.AddIndex(
            model_name='heatmapdata',
            index=models.Index(fields=['project', 'page_url', 'date'], name='analytics_h_project_1cdaba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='heatmapdata',
            unique_together={('project', 'page_url', 'x_coordinate', 'y_coordinate', 'date')},
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['page_view', 'event_type'], name='analytics_u_page_vi_e41bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['timestamp'], name='analytics_u_timesta_c496d4_idx'),
        ),
    ]
