# Generated by Django 5.0.9 on 2025-07-28 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], help_text='A/Bテストのバリアント', max_length=1)),
                ('event', models.CharField(choices=[('page_view', 'Page View'), ('register_click', 'Register Click'), ('login_click', 'Login Click'), ('conversion', 'Conversion')], help_text='イベントタイプ', max_length=20)),
                ('timestamp', models.BigIntegerField(help_text='フロントエンドから送信されたタイムスタンプ')),
                ('session_id', models.CharField(help_text='セッションID', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='ユーザーID（コンバージョン時のみ）', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IPアドレス（統計用）', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='ユーザーエージェント（統計用）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='レコード作成日時')),
            ],
            options={
                'verbose_name': 'A/Bテストイベント',
                'verbose_name_plural': 'A/Bテストイベント',
                'db_table': 'ab_test_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'event'], name='idx_variant_event'), models.Index(fields=['timestamp'], name='idx_timestamp'), models.Index(fields=['session_id'], name='idx_session_id'), models.Index(fields=['created_at'], name='idx_created_at')],
            },
        ),
        migrations.CreateModel(
            name='ABTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='セッションID', max_length=100, unique=True)),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], help_text='このセッションに割り当てられたバリアント', max_length=1)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now, help_text='初回訪問日時')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='最終活動日時')),
                ('converted', models.BooleanField(default=False, help_text='コンバージョン済みフラグ')),
                ('conversion_date', models.DateTimeField(blank=True, help_text='コンバージョン日時', null=True)),
            ],
            options={
                'verbose_name': 'A/Bテストセッション',
                'verbose_name_plural': 'A/Bテストセッション',
                'db_table': 'ab_test_sessions',
                'ordering': ['-first_visit'],
                'indexes': [models.Index(fields=['variant'], name='idx_session_variant'), models.Index(fields=['converted'], name='idx_session_converted'), models.Index(fields=['first_visit'], name='idx_session_first_visit')],
            },
        ),
        migrations.CreateModel(
            name='ABTestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='集計対象日')),
                ('variant', models.CharField(choices=[('A', 'Variant A'), ('B', 'Variant B')], help_text='バリアント', max_length=1)),
                ('page_views', models.IntegerField(default=0, help_text='ページビュー数')),
                ('register_clicks', models.IntegerField(default=0, help_text='登録ボタンクリック数')),
                ('login_clicks', models.IntegerField(default=0, help_text='ログインボタンクリック数')),
                ('conversions', models.IntegerField(default=0, help_text='コンバージョン数')),
                ('unique_sessions', models.IntegerField(default=0, help_text='ユニークセッション数')),
                ('conversion_rate', models.FloatField(default=0.0, help_text='コンバージョン率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'A/Bテストサマリー',
                'verbose_name_plural': 'A/Bテストサマリー',
                'db_table': 'ab_test_summary',
                'ordering': ['-date', 'variant'],
                'indexes': [models.Index(fields=['date', 'variant'], name='idx_summary_date_variant'), models.Index(fields=['date'], name='idx_summary_date')],
                'unique_together': {('date', 'variant')},
            },
        ),
    ]
