# Generated by Django 5.0.9 on 2025-07-19 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='bot_process_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ボットプロセスID'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='予約録画フラグ'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meeting_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='会議詳細情報'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meeting_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='会議番号'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meeting_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='会議タイトル'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meeting_url',
            field=models.URLField(blank=True, null=True, verbose_name='会議URL'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='recording_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='録画終了時刻'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='recording_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='録画開始時刻'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約開始時刻'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='source_type',
            field=models.CharField(default='upload', max_length=20, verbose_name='ソース種別'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='zoom_session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ZoomセッションID'),
        ),
        migrations.CreateModel(
            name='ScheduledRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(max_length=20, verbose_name='会議ID')),
                ('meeting_topic', models.CharField(blank=True, max_length=255, verbose_name='会議タイトル')),
                ('meeting_url', models.URLField(verbose_name='会議URL')),
                ('meeting_password', models.CharField(blank=True, max_length=50, verbose_name='会議パスワード')),
                ('host_email', models.EmailField(blank=True, max_length=254, verbose_name='主催者メール')),
                ('scheduled_start_time', models.DateTimeField(verbose_name='予約開始時刻')),
                ('scheduled_end_time', models.DateTimeField(blank=True, null=True, verbose_name='予約終了時刻')),
                ('estimated_duration', models.IntegerField(default=60, verbose_name='予想時間（分）')),
                ('timezone_name', models.CharField(default='Asia/Tokyo', max_length=50, verbose_name='タイムゾーン')),
                ('recording_type', models.CharField(choices=[('immediate', '即時録画'), ('scheduled', '予約録画'), ('recurring', '定期録画')], default='scheduled', max_length=20, verbose_name='録画種別')),
                ('auto_start', models.BooleanField(default=True, verbose_name='自動開始')),
                ('auto_stop', models.BooleanField(default=True, verbose_name='自動停止')),
                ('pre_recording_minutes', models.IntegerField(default=5, verbose_name='録画開始前余裕時間（分）')),
                ('post_recording_minutes', models.IntegerField(default=10, verbose_name='録画終了後余裕時間（分）')),
                ('status', models.CharField(choices=[('scheduled', '予約済み'), ('preparing', '準備中'), ('recording', '録画中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='scheduled', max_length=20, verbose_name='状態')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='CeleryタスクID')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='実際の開始時刻')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='実際の終了時刻')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('meeting_details', models.JSONField(blank=True, default=dict, verbose_name='会議詳細情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_recordings', to='voice_picker.uploadedfile')),
            ],
            options={
                'verbose_name': '予約録画',
                'verbose_name_plural': '予約録画',
                'db_table': 'scheduled_recordings',
                'indexes': [models.Index(fields=['scheduled_start_time'], name='scheduled_r_schedul_94c3bf_idx'), models.Index(fields=['status'], name='scheduled_r_status_68b973_idx'), models.Index(fields=['meeting_id'], name='scheduled_r_meeting_551600_idx')],
            },
        ),
    ]
