# Generated by Django 5.0.9 on 2025-07-21 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_picker', '0002_uploadedfile_bot_process_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='bot_process_id',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='meeting_details',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='meeting_number',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='meeting_topic',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='meeting_url',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='recording_end_time',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='recording_start_time',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='scheduled_start_time',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='zoom_session_id',
        ),
    ]
