# Generated by Django 5.0.9 on 2025-07-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_picker', '0003_remove_uploadedfile_bot_process_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='issue_generation_count',
            field=models.IntegerField(default=0, verbose_name='課題再生成回数'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='solution_generation_count',
            field=models.IntegerField(default=0, verbose_name='取り組み案再生成回数'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='summarization_generation_count',
            field=models.IntegerField(default=0, verbose_name='要約再生成回数'),
        ),
        migrations.DeleteModel(
            name='MeetingRecording',
        ),
    ]
