# Generated by Django 5.1.4 on 2025-01-21 XX:XX

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member_management', '0004_campaigntracking_is_manual_referral_and_more'),
        ('voice_picker', '0004_uploadedfile_issue_generation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_type', models.CharField(choices=[('summary', '要約'), ('issues', '課題'), ('solutions', '取り組み案')], max_length=20, verbose_name='プロンプト種別')),
                ('custom_instruction', models.TextField(blank=True, null=True, verbose_name='カスタム指示')),
                ('generated_result', models.TextField(blank=True, null=True, verbose_name='生成結果')),
                ('week_of_year', models.IntegerField(verbose_name='年の何週目')),
                ('year', models.IntegerField(verbose_name='年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('instruction_keywords', models.JSONField(blank=True, default=list, help_text='分析用のキーワードリスト', verbose_name='指示キーワード')),
                ('instruction_category', models.CharField(blank=True, help_text='技術的、ビジネス、改善案など', max_length=50, null=True, verbose_name='指示カテゴリ')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_histories', to='member_management.organization', verbose_name='組織')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_histories', to='voice_picker.uploadedfile', verbose_name='対象ファイル')),
            ],
            options={
                'verbose_name': 'プロンプト履歴',
                'verbose_name_plural': 'プロンプト履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prompthistory',
            index=models.Index(fields=['organization', 'week_of_year', 'year'], name='voice_picke_organiz_9d7988_idx'),
        ),
        migrations.AddIndex(
            model_name='prompthistory',
            index=models.Index(fields=['prompt_type', 'created_at'], name='voice_picke_prompt__56d05f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompthistory',
            index=models.Index(fields=['instruction_category'], name='voice_picke_instruc_adfdc4_idx'),
        ),
    ]