# Generated by Django 5.0.9 on 2025-08-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_picker', '0005_prompthistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='prompthistory',
            new_name='voice_picke_organiz_8b2857_idx',
            old_name='voice_picke_organiz_9d7988_idx',
        ),
        migrations.RenameIndex(
            model_name='prompthistory',
            new_name='voice_picke_prompt__95887d_idx',
            old_name='voice_picke_prompt__56d05f_idx',
        ),
        migrations.RenameIndex(
            model_name='prompthistory',
            new_name='voice_picke_instruc_d8b7c7_idx',
            old_name='voice_picke_instruc_adfdc4_idx',
        ),
    ]
